version: "3"

services:
  ytrank-postgres-compose:
    image: ${DB_CONNECTION-postgres}
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASS:-123}
      POSTGRES_DB: "${DB_NAME:-postgres}"
    ports:
      - "15432:${DB_PORT:-5432}"
    volumes:
      - ${DB_LOCAL_VOLUME:-postgres:/data/postgres}
    networks:
      - postgres-compose-network

  ytrank-pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-123}
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    depends_on:
      - ytrank-postgres-compose
    networks:
      - postgres-compose-network

  app:
    build:
      context: .
      dockerfile: Dockerfile.${APP_ENV:-env}
    env_file:
      - .env
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "5000:${PORT:-5000}"
    depends_on:
      - ytrank-postgres-compose
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge
